version: "3"
services:
  node-image:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    env_file:
      - ./.env
    command: npm run dev

  mongo:
    env_file:
      - ./.env
