version: "3"
services:
  node-image:
    build:
      context: .
      args:
        NODE_ENV: production
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=production
    command: node index.js
