version: "3"
services:
  node-image:
    build: .
    ports:
      - "3000:4001"
    volumes:
      - ./:/app
      - /app/node_modules
    # environment:
    #   - PORT=3000
    env_file:
      - ./.env
