version: "3"
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - "3000:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  node-image:
    build: .
    env_file:
      - ./.env
    depends_on:
      - mongo

  mongo:
    image: mongo
    env_file:
      - ./.env
    volumes:
      - name_db_volume:/data/db

  redis:
    image: redis
    env_file:
      - ./.env

volumes:
  name_db_volume:
