@baseURL = http://localhost:3000/api/v1/posts

GET http://localhost:3000/api/v1

### Get all posts
GET {{baseURL}}

### Get a post
GET {{baseURL}}/618cb9f8d42713aed59091ca

### Create post
POST {{baseURL}}
content-type: application/json

{
  "title": "My first post 2",
  "body": "This is my first post 2"
}

### Update post
PATCH {{baseURL}}/618cb9f8d42713aed59091ca
content-type: application/json

{
  "title": "My first post 2",
  "body": "This is my first post 2"
}

### Delete post
DELETE {{baseURL}}/618cb9f8d42713aed59091ca
content-type: application/json
